---
title: "Week 1 EDA"
author: "Wuji Shan, Guangze Yu"
date: "4/3/2022"
output: pdf_document
---

```{r}
# source("Data Wrangling.R")
# source("functions used.R")
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
full <- cbind(IDinfo, discrete)
left <- full %>% filter(KNEE == "LEFT")
right <- full %>% filter(KNEE == "RIGHT")
```

```{r}
trial1l <- trial(left,"1")
trial1r <- trial(right,"1")
trial2l <- trial(left,"2")
trial2r <- trial(right,"2")
trial3l <- trial(left,"3")
trial3r <- trial(right,"3")
trial4l <- trial(left,"4")
trial4r <- trial(right,"4")
trial5l <- trial(left,"5")
trial5r <- trial(right,"5")
trialset <- c('1l', '1r', '2l', '2r', '3l', '3r', '4l', '4r', '5l', '5r')
mean_trial_length <- rbind(mean(trial1l$tr_length), mean(trial1r$tr_length),
                         mean(trial2l$tr_length), mean(trial2r$tr_length),
                         mean(trial3l$tr_length), mean(trial3r$tr_length),
                         mean(trial4l$tr_length), mean(trial4r$tr_length),
                         mean(trial5l$tr_length), mean(trial5r$tr_length))
mean_length <- data.frame(trialset, mean_trial_length)
mean_length_left <- data.frame(c('1', '2', '3', '4', '5'),
                               rbind(mean(trial1l$tr_length),mean(trial2l$tr_length),
                                     mean(trial3l$tr_length),mean(trial4l$tr_length),
                                     mean(trial5l$tr_length)))
colnames(mean_length_left) <- c('trialset_left', 'mean_left')
mean_length_right <- data.frame(c('1', '2', '3', '4', '5'),
                               rbind(mean(trial1r$tr_length),mean(trial2r$tr_length),
                                     mean(trial3r$tr_length),mean(trial4r$tr_length),
                                     mean(trial5r$tr_length)))
colnames(mean_length_right) <- c('trialset_right', 'mean_right')

ggplot() + 
  geom_line(data = mean_length_left, aes(x = trialset_left, y = mean_left), 
            group = 1, color = "red") + 
  geom_line(data = mean_length_right, aes(x = trialset_right, y = mean_right), 
            group = 1, color = "blue") + 
  xlab("Trial Number") + ylab("Mean of tr_length")
```

```{r}
difference <- data.frame(c('left','right'),
                         c(mean(left$vGRF_impulse), mean(right$vGRF_impulse)),
                         c(mean(left$mGRF_impulse), mean(right$mGRF_impulse)),
                         c(mean(left$lGRF_impulse), mean(right$lGRF_impulse)),
                         c(mean(left$aGRF_impulse), mean(right$aGRF_impulse)),
                         c(mean(left$pGRF_impulse), mean(right$pGRF_impulse)),
                         c(mean(left$stancetime), mean(right$stancetime)),
                         c(mean(left$TO_angle), mean(right$TO_angle)),
                         c(mean(left$vGRF_avgLR), mean(right$vGRF_avgLR)),
                         c(mean(left$vGRF_iLR_max), mean(right$vGRF_iLR_max)),
                         c(mean(left$vGRF_avgULR), mean(right$vGRF_avgULR)),
                         c(mean(left$vGRF_iULR_max), mean(right$vGRF_iULR_max)),
                         c(mean(left$vGRF_peak1), mean(right$vGRF_peak1)),
                         c(mean(left$vGRF_peak2), mean(right$vGRF_peak2)),
                         c(mean(left$vGRF_valley), mean(right$vGRF_valley)))
colnames(difference) <- c('KNEE','vGRF_impulse','mGRF_impulse','lGRF_impulse',
                          'aGRF_impulse','pGRF_impulse','stancetime','TO_angle',
                          'vGRF_avgLR', 'vGRF_iLR_max','vGRF_avgULR',
                          'vGRF_iULR_max','vGRF_peak1','vGRF_peak2','vGRF_valley')
```
```{r}
ggplot() + 
  geom_line(data = difference, aes(x = KNEE, y = vGRF_impulse, color = "vGRF_impulse"), 
            group = 1) + 
  geom_line(data = difference, aes(x = KNEE, y = mGRF_impulse, color = "mGRF_impulse"), 
            group = 1) + 
  geom_line(data = difference, aes(x = KNEE, y = lGRF_impulse, color = "lGRF_impulse"), 
            group = 1) + 
  geom_line(data = difference, aes(x = KNEE, y = aGRF_impulse, color = "aGRF_impulse"), 
            group = 1) + 
  geom_line(data = difference, aes(x = KNEE, y = pGRF_impulse, color = "pGRF_impulse"), 
            group = 1) + 
  geom_line(data = difference, aes(x = KNEE, y = stancetime, color = "stancetime"), 
            group = 1) + 
  geom_line(data = difference, aes(x = KNEE, y = TO_angle, color = "TO_angle"), 
            group = 1) +
  geom_line(data = difference2, aes(x = KNEE, y = vGRF_avgLR, color = "vGRF_avgLR"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = vGRF_iLR_max, color = "vGRF_iLR_max"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = vGRF_avgULR, color = "vGRF_avgULR"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = vGRF_iULR_max, color = "vGRF_iULR_max"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = vGRF_peak1, color = "vGRF_peak1"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = vGRF_peak2, color = "vGRF_peak2"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = vGRF_valley, color = "vGRF_valley"), 
            group = 1) +
  xlab("KNEE") + ylab("mean")
```

```{r}
difference2 <- data.frame(c('left','right'),
                         c(mean(left$apGRF_peak1), mean(right$apGRF_peak1)),
                         c(mean(left$apGRF_peak2), mean(right$apGRF_peak2)),
                         c(mean(left$mlGRF_peak1), mean(right$mlGRF_peak1)),
                         c(mean(left$mlGRF_peak2), mean(right$mlGRF_peak2)),
                         c(mean(left$mlGRF_peak3), mean(right$mlGRF_peak3)),
                         c(mean(left$t_vGRF_iLR_max_PERC), mean(right$t_vGRF_iLR_max_PERC)),
                         c(mean(left$t_vGRF_iULR_max_PERC),mean(right$t_vGRF_iULR_max_PERC)),
                         c(mean(left$t_vGRF_peak1_PERC), mean(right$t_vGRF_peak1_PERC)),
                         c(mean(left$t_vGRF_peak2_PERC), mean(right$t_vGRF_peak2_PERC)),
                         c(mean(left$t_vGRF_valley_PERC), mean(right$t_vGRF_valley_PERC)),
                         c(mean(left$t_apGRF_peak1_PERC), mean(right$t_apGRF_peak1_PERC)),
                         c(mean(left$t_apGRF_peak2_PERC), mean(right$t_apGRF_peak2_PERC)),
                         c(mean(left$t_mlGRF_peak1_PERC), mean(right$t_mlGRF_peak1_PERC)),
                         c(mean(left$t_mlGRF_peak2_PERC), mean(right$t_mlGRF_peak2_PERC)),
                         c(mean(left$t_mlGRF_peak3_PERC), mean(right$t_mlGRF_peak3_PERC)))
colnames(difference2) <- c('KNEE','apGRF_peak1','apGRF_peak2',
                           'mlGRF_peak1','mlGRF_peak2','mlGRF_peak3',
                           't_vGRF_iLR_max_PERC','t_vGRF_iULR_max_PERC',
                           't_vGRF_peak1_PERC','t_vGRF_peak2_PERC',
                           't_vGRF_valley_PERC','t_apGRF_peak1_PERC','t_apGRF_peak2_PERC',
                           't_mlGRF_peak1_PERC','t_mlGRF_peak2_PERC','t_mlGRF_peak3_PERC')
```
```{r}
ggplot() + 
  geom_line(data = difference2, aes(x = KNEE, y = apGRF_peak1, color = "apGRF_peak1"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = apGRF_peak2, color = "apGRF_peak2"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = mlGRF_peak1, color = "mlGRF_peak1"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = mlGRF_peak2, color = "mlGRF_peak2"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = mlGRF_peak3, color = "mlGRF_peak3"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = t_vGRF_iLR_max_PERC, color = "t_vGRF_iLR_max_PERC"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = t_vGRF_iULR_max_PERC, color = "t_vGRF_iULR_max_PERC"), 
            group = 1) +
  geom_line(data = difference2, aes(x = KNEE, y = t_vGRF_peak1_PERC, color = "t_vGRF_peak1_PERC"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = t_vGRF_peak2_PERC, color = "t_vGRF_peak2_PERC"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = t_vGRF_valley_PERC, color = "t_vGRF_valley_PERC"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = t_apGRF_peak1_PERC, color = "t_apGRF_peak1_PERC"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = t_apGRF_peak2_PERC, color = "t_apGRF_peak2_PERC"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = t_mlGRF_peak1_PERC, color = "t_mlGRF_peak1_PERC"), 
            group = 1) + 
  geom_line(data = difference2, aes(x = KNEE, y = t_mlGRF_peak2_PERC, color = "t_mlGRF_peak2_PERC"), 
            group = 1) +
  geom_line(data = difference2, aes(x = KNEE, y = t_mlGRF_peak3_PERC, color = "t_mlGRF_peak3_PERC"), 
            group = 1) +
  xlab("KNEE") + ylab("mean")
```




